### PR TITLE
Add Russian translation, made by yota13.

### PR DESCRIPTION
**Pull request by abalabokhin**

### CODE REVIEW

**Comment by 11jo** [comment]
There is no Usable By: / Not Usable By: in item descriptions.

**Comment by abalabokhin** [comment]
I know, originally this translation was done for Roxanna's version (that is EE only) and "Usable By" wasn't added after it. I don't have time to do it now and I don't think yota13 is going to do it either. Thus, I decided to send the translation as is. If you believe that it should be done properly, don't accept the pull request for now, I will add "Usable By" sooner or later.

**Comment by abalabokhin** [comment]
I updated the Russian translation with Usable By: / Not Usable By information and tested the mod installation on EE to make sure that it is removed properly for EE. Can you accept the pull request, please?

**Comment by 11jo** [comment]
Of course, thanks @abalabokhin !

Edit : I will set the release tomorow.

**Pull request merged**
